In [1]:
# 문자열 함수
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [2]:
# 문자열 함수 str함수 -startswith('강'): 강으로 시작되는 이름
df[df['이름'].str.startswith('강')] # 이름이 강으로 시작되는 사람 찾기
df.loc[df['이름'].str.startswith('강')]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [3]:
df = pd.read_excel("file/students.xlsx", index_col='번호')
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [13]:
df[df['이름'].str.startswith("강")]
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [14]:
df[df['이름'].str.contains('열')]

Empty DataFrame
Columns: [이름, 학교, 학년, 키, 국어, 영어, 수학, SW특기]
Index: []

In [15]:
df[~df['이름'].str.contains('열')]

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [17]:
# lower, upper
df['SW특기'].str.lower()

번호
1           c
2           c
3           c
4           c
5           c
        ...
96     python
97     python
98          c
99     python
100      java
Name: SW특기, Length: 100, dtype: str

In [18]:
df['SW특기'].str.upper()

번호
1           C
2           C
3           C
4           C
5           C
        ...
96     PYTHON
97     PYTHON
98          C
99     PYTHON
100      JAVA
Name: SW특기, Length: 100, dtype: str

In [21]:
df['SW특기'].str.capitalize()

번호
1           C
2           C
3           C
4           C
5           C
        ...
96     Python
97     Python
98          C
99     Python
100      Java
Name: SW특기, Length: 100, dtype: str

In [22]:
df[df['SW특기'].str.startswith('J')]

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
55     Emmanuel   구로고   2  191  63  27  83        JAVA
65         Kiri   신림고   3  178  64  83  68        JAVA
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
84          Ola  디지털고   3  170  84  77  77  Javascript
91       Marika   신림고   2  189  89  22  32  Javascript
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA

In [24]:
# 여러개 검색['python','java']로 시작하는 것 탐색
langs = ['python','java']
df[df['SW특기'].str.lower().isin(langs)] # SW특기에 있는 값들을 소문자로 모두 바꾼 후 리스트 검색

              이름    학교  학년    키  국어  영어  수학    SW특기
번호
7           Gaye   신림고   3  192  65  27  86  PYTHON
10         Honor   신림고   2  186  83  11  58  PYTHON
12        Lenora  디지털고   2  198  81  75  30  python
13        Ardene  디지털고   2  161  91  97  33    JAVA
14       Sibylle   구로고   1  197  82  81  38    JAVA
15       Annette  디지털고   2  177  92  41  32  Python
17         Alric   구로고   1  193  68  96  76    JAVA
18         Mozes   신림고   1  176  61  44  51    JAVA
19      Brigitta   구로고   2  175  54  61  73  PYTHON
21     Evangelia   신림고   2  190  51  71  83  PYTHON
24          Rici  디지털고   3  196  72  42  54  Python
25         Robin   구로고   2  187  64  44  89  PYTHON
26      Filberte  디지털고   2  194  66   0  39  python
27        Gordan  디지털고   1  183  90  31  90  PYTHON
29       Timoteo   신림고   2  209  77  94  67  Python
31        Holmes   구로고   1  184  51  21  87  Python
33      Robinson  디지털고   2  181  55  83  70  PYTHON
38         Corry  디지털고   3  162  93  12  35  PYTHON
39           Ban   구로고   1  185  82  94  80  Python
40         Aimil  디지털고   2  207  65  14  86  Python
43          Dale   신림고   2  192  91  96  55  PYTHON
47        Perkin  디지털고   2  169  82  73  62  python
48   Worthington   신림고   1  210  52  67  70  Python
50       Nicolai   신림고   1  176  78  13  75  PYTHON
53    Anthiathia   신림고   3  178  76   7  52  python
54           Ula   신림고   3  168  80  59  85    java
55      Emmanuel   구로고   2  191  63  27  83    JAVA
56         Valle   신림고   3  167  68  83  52    java
59       Kessiah  디지털고   2  162  66   0  67  PYTHON
60       Malynda  디지털고   1  178  57  79  72    java
63        Sarene   구로고   3  190  76  59  58  PYTHON
65          Kiri   신림고   3  178  64  83  68    JAVA
66        Joanie   신림고   1  200  75  24  85    java
68         Tresa   구로고   2  166  58  37  70    java
69        Gerard  디지털고   1  183  64  54  56  Python
70         Gilda   구로고   3  189  71  43  89  Python
71         Booth   신림고   3  208  86  53  44  python
73         Moise  디지털고   3  185  90  83  65    JAVA
74         Lewes  디지털고   2  187  61  22  43    JAVA
77         Lorna   신림고   1  208  99  98  86  Python
80        Dallas   신림고   2  173  65  33  45  Python
81        Yancey   신림고   3  185  87  92  66  python
82        Jamill   구로고   2  182  98   8  60    java
83       Michael   신림고   2  190  77  32  66  Python
85       Diahann   신림고   3  189  90  26  83  PYTHON
86       Gweneth  디지털고   1  201  86   5  67  Python
87      Meredith   구로고   3  186  55  17  41  python
88         Emile   신림고   2  199  83  26  68  PYTHON
89        Norris  디지털고   3  174  68   9  51    java
92        Bobbie   구로고   3  188  86  47  42  PYTHON
94          Kaja   신림고   1  202  53  44  78    java
95    Clementine   신림고   1  194  71  13  81    JAVA
96          Luke   신림고   3  187  91  63  59  Python
97          Nada   구로고   3  170  60  89  55  PYTHON
99          Leif   구로고   2  192  96  84  34  PYTHON
100     Jonathan  디지털고   2  195  84  63  80    JAVA

In [26]:
### 문자열 함수 -> .str을 붙여야 함 **** java가 포함된 것으로 모두 찾으려고 함

df['SW특기']
df['SW특기'].str.contains("java",na=False) # SW특가에 있는 모든 값의 알파벳을 모두 소문자로 변환시켜서 java가 포함되었는 지 판정 -> 만약, Nan값이 있으면, 에러처리되므로 na=False 처리해야 됨
df[df['SW특기'].str.contains("java",na=True)] # na=True 처리하면 Nan데이터도 출력, False는 출력하지 않음
df[df['SW특기'].str.lower().str.contains("java",na=True)] # 소문자로 변경 후 검색

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
54          Ula   신림고   3  168  80  59  85        java
55     Emmanuel   구로고   2  191  63  27  83        JAVA
56        Valle   신림고   3  167  68  83  52        java
60      Malynda  디지털고   1  178  57  79  72        java
65         Kiri   신림고   3  178  64  83  68        JAVA
66       Joanie   신림고   1  200  75  24  85        java
68        Tresa   구로고   2  166  58  37  70        java
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
82       Jamill   구로고   2  182  98   8  60        java
84          Ola  디지털고   3  170  84  77  77  Javascript
89       Norris  디지털고   3  174  68   9  51        java
91       Marika   신림고   2  189  89  22  32  Javascript
94         Kaja   신림고   1  202  53  44  78        java
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA

In [ ]:
# 문자열 함수 : startswith, endswith, contains, lower, upper, capitalize
# split, strip, find
#

In [29]:
# unique : 중복 제거
df['학교'].unique()

<StringArray>
['신림고', '구로고', '디지털고']
Length: 3, dtype: str

In [31]:
df = pd.read_csv("file/drinks.csv")
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [32]:
df['continent'] # 결과치가 너무 많음 -> 몇 개 대륙 및 국가인지 알고 싶으면

0      AS
1      EU
2      AF
3      EU
4      AF
       ..
188    SA
189    AS
190    AS
191    AF
192    AF
Name: continent, Length: 193, dtype: str

In [33]:
df['continent'].unique()

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [34]:
df = pd.read_excel("file/합계출산율_2026.xlsx",skiprows=28,nrows=2)
df

,Unnamed: 0,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
1,합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [36]:
df = pd.read_excel("file/연령별인구현황_2025.xlsx",skiprows=3)
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,행정기관코드,행정기관,총 인구수,연령구간인구수,0~9세,10~19세,20~29세,30~39세,40~49세,50~59세,...,10~19세.17,20~29세.17,30~39세.17,40~49세.17,50~59세.17,60~69세.17,70~79세.17,80~89세.17,90~99세.17,100세 이상.17
0,0,전국,"51,159,889","51,159,889","3,024,945","4,630,054","5,800,511","6,649,487","7,627,071","8,684,663",...,"2,252,500","2,731,714","3,183,648","3,722,461","4,279,301","4,015,237","2,434,888","1,334,492","276,634","7,285"
1,1100000000,서울특별시,"9,323,492","9,323,492","468,816","721,320","1,283,295","1,453,915","1,370,576","1,479,906",...,"351,202","668,158","731,594","690,464","745,790","693,675","454,809","217,852","39,589","1,122"
2,2600000000,부산광역시,"3,251,625","3,251,625","174,385","264,105","347,001","388,293","464,061","533,582",...,"129,117","166,150","187,510","227,270","269,150","293,502","200,839","93,279","15,912",380
3,2700000000,대구광역시,"2,357,040","2,357,040","137,277","212,852","259,482","284,076","338,976","415,287",...,"103,673","120,683","132,982","168,373","211,040","198,463","123,774","64,137","11,751",244
4,2800000000,인천광역시,"3,041,215","3,041,215","191,580","275,205","343,681","427,940","474,175","517,186",...,"134,628","163,718","206,089","229,629","257,977","240,110","125,153","63,740","13,996",458
5,2900000000,광주광역시,"1,398,538","1,398,538","88,569","144,440","175,332","173,489","215,553","242,861",...,"69,794","81,483","83,278","106,651","121,311","101,060","61,179","31,734","6,292",166
6,3000000000,대전광역시,"1,440,682","1,440,682","88,295","135,988","190,311","193,281","210,477","243,133",...,"65,946","89,881","91,114","104,303","121,309","107,446","62,207","31,741","6,550",176
7,3100000000,울산광역시,"1,093,317","1,093,317","69,400","109,461","113,355","136,397","170,157","200,521",...,"52,823","46,580","61,167","81,241","98,972","88,639","44,472","18,631","3,489",89
8,3600000000,세종특별자치시,"392,154","392,154","39,786","53,598","36,705","58,404","76,817","58,448",...,"26,728","17,838","29,199","38,974","28,381","19,862","10,228","5,194","1,395",32
9,4100000000,경기도,"13,715,016","13,715,016","907,966","1,326,019","1,588,251","1,915,357","2,191,701","2,362,358",...,"648,817","742,934","915,920","1,068,642","1,170,928","986,112","527,550","279,834","58,507","1,633"
10,5100000000,강원특별자치도,"1,510,181","1,510,181","82,465","125,810","150,649","158,114","196,699","259,571",...,"60,644","65,189","73,267","95,523","124,755","139,733","84,538","55,039","11,453",341
11,4300000000,충청북도,"1,591,815","1,591,815","94,765","143,089","169,353","190,906","222,510","272,442",...,"69,467","74,640","86,257","106,113","131,858","132,773","77,318","48,254","10,635",265
12,4400000000,충청남도,"2,136,299","2,136,299","129,729","202,517","215,443","252,062","315,039","352,172",...,"98,037","94,918","113,744","146,403","165,330","166,044","106,496","69,342","17,347",392
13,5200000000,전북특별자치도,"1,729,337","1,729,337","90,407","160,265","175,875","172,529","229,830","300,777",...,"77,272","78,685","81,976","111,200","143,488","144,774","102,514","66,540","15,540",395
14,4600000000,전라남도,"1,782,183","1,782,183","97,751","155,618","163,051","169,648","229,537","306,612",...,"75,733","70,397","79,764","107,206","140,031","152,848","108,514","81,064","17,677",462
15,4700000000,경상북도,"2,516,753","2,516,753","133,226","215,714","226,544","253,958","337,104","437,680",...,"102,800","94,261","113,367","158,982","208,554","227,862","151,342","96,308","21,422",499
16,4800000000,경상남도,"3,214,016","3,214,016","184,989","314,002","295,003","343,941","480,612","582,384",...,"151,701","125,619","158,639","230,658","282,962","273,340","165,166","94,298","20,302",447
17,5000000000,제주특별자치도,"666,226","666,226","45,539","70,051","67,180","77,177","103,247","119,743",...,"34,118","30,580","37,781","50,829","57,465","48,994","28,789","17,505","4,777",184

In [43]:
# 총인구수 출력
df = df.iloc[0,2]

In [44]:
# 총인구수를 숫자로 변환

AttributeError: 'str' object has no attribute 'iloc'

In [45]:
# 문자열 함수
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [46]:
df = pd.read_excel("file/students.xlsx",index_col="번호")

In [51]:
# s가 있는 이름을 모두 출력하시오. 대문자, 소문자 모두 확인
# 명령문에 1개이면 str없이 사용, 여러개일 때 str 입력 후 사용
df[df['이름'].str.lower().str.contains('s')] 
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [52]:
df['총 인구수'] = df['총 인구수'].str.replace(",","").astype(int) # 숫자로 변환하려면, 1개만 변환은 안됨. 컬럼 전체를 컬럼으로 전환해야 함

KeyError: '총 인구수'

In [53]:
df =pd.read_excel("file/students.xlsx",index_col="번호")
df['학교'] = df['학교'].str.replace('고','고등학교')
df['학교']

번호
1       신림고등학교
2       구로고등학교
3       구로고등학교
4       구로고등학교
5      디지털고등학교
        ...
96      신림고등학교
97      구로고등학교
98      신림고등학교
99      구로고등학교
100    디지털고등학교
Name: 학교, Length: 100, dtype: str

In [61]:
df['학교'] = df['학교']+'등학교' # 이렇게로도 변경 가능
df['학교']

번호
1       신림고등학교
2       구로고등학교
3       구로고등학교
4       구로고등학교
5      디지털고등학교
        ...
96      신림고등학교
97      구로고등학교
98      신림고등학교
99      구로고등학교
100    디지털고등학교
Name: 학교, Length: 100, dtype: str

In [64]:
df = pd.read_excel("file/students.xlsx",index_col="번호")
# SW특기에서 java, c인 것을 찾아라

langs = ['java', 'c']
# df[df['SW특기'].str.lower.str.contains(langs)['SW특기']]

In [63]:
df[df['SW특기'].str.lower.str.contains('java',na=False)]

AttributeError: 'function' object has no attribute 'str'