In [22]:
import pandas as pd
import numpy as np
df = pd.read_excel("file/score.xlsx",index_col="지원번호")

In [23]:
# NaN처리(결측치 처리)
# fillna : nan를 채워줌

df.fillna(' ',inplace=True) # 결측치는 공백(" ") 처리
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80
5번    김재욱   신림고  188   15   20   10  35  10
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [26]:
# 학교 컬럼을 모두 nan처리 :
# np.nan : numpy명령어, nan데이터를 모두 입력
# numpy는 숫자만 가능, 문자는 안됨
df['학교'] = np.nan
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래 NaN  197   90   85  100  95  85      Python
2번    강태원 NaN  184   40   35   50  55  25        Java
3번    강호림 NaN  168   80   75   70  80  75  Javascript
4번    김수찬 NaN  187   40   60   70  75  80
5번    김재욱 NaN  188   15   20   10  35  10
6번    박동현 NaN  202   80  100   95  85  80           C
7번    박혜정 NaN  188   55   65   45  40  35      PYTHON
8번    승근열 NaN  190  100   85   90  95  95          C#

In [ ]:
df.fillna("없음", inplace=True)

TypeError: Invalid value '없음' for dtype 'float64'

In [ ]:
#  Nan 데이터 삭제 : dropna -> nan이 포함된 모든 행을 지움. axis는 방향, how는 범위
df['학교'] = df['학교'].astype('object')
df.dropna(how='any',axis="index") # how: any - 1개만 있어도 삭제 -> 5, 6번 삭제
df.dropna(how='all',axis="index") # how: all - 모두 있어야 삭제 -> 삭제 안됨
df.dropna(how="any", axis='columns') # axis는 index, columns가 있음. 전자는 인덱스 방향, rows가로 삭제, columns는 사로삭제
df

Empty DataFrame
Columns: [이름, 학교, 키, 국어, 영어, 수학, 과학, 사회, SW특기]
Index: []

In [ ]:
df['학교'] = np.nan