In [4]:
import pandas as pd

In [5]:
data = {
    '이름':['강나래','강태원','강호림','김수찬','김재욱','박동현','박혜정','승근열'],
    '학교':['신림고','신림고','신림고','신림고','신림고','디지털고','디지털고','디지털고'] ,
    '키':[197,184,168,187,188,202,188,190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']}

In [8]:
df = pd.DataFrame(data) # 기능이 많고 속도가 빨라서 데이터프레임으로 전환
df

    이름    학교    키   국어   영어   수학  과학  사회        SW특기
0  강나래   신림고  197   90   85  100  95  85      Python
1  강태원   신림고  184   40   35   50  55  25        Java
2  강호림   신림고  168   80   75   70  80  75  Javascript
3  김수찬   신림고  187   40   60   70  75  80
4  김재욱   신림고  188   15   20   10  35  10
5  박동현  디지털고  202   80  100   95  85  80           C
6  박혜정  디지털고  188   55   65   45  40  35      PYTHON
7  승근열  디지털고  190  100   85   90  95  95          C#

In [9]:
df = pd.DataFrame(data, ["1번","2번","3번","4번","5번","6번","7번","8번"])
df.index.name="지원번호"
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80
5번    김재욱   신림고  188   15   20   10  35  10
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [10]:
# 파일로 저장, csv, txt, xlsx
df.to_csv("file/score.csv",encoding='utf-8-sig') # txt만 encoding 필요

In [11]:
df.to_csv("file/score.txt", sep="\t")

In [12]:
df.to_excel("file/score.xlsx")

In [13]:
# 파일 읽기
df =pd.read_csv("file/score.csv")
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기
0   1번  강나래   신림고  197   90   85  100  95  85      Python
1   2번  강태원   신림고  184   40   35   50  55  25        Java
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN
5   6번  박동현  디지털고  202   80  100   95  85  80           C
6   7번  박혜정  디지털고  188   55   65   45  40  35      PYTHON
7   8번  승근열  디지털고  190  100   85   90  95  95          C#

In [14]:
# 인덱스를 지원번호로 지정
df.set_index("지원번호",inplace=True)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [15]:
df =pd.read_excel("file/score.xlsx")

In [ ]:
## 대제목
# markdown은 설명문 설정

In [18]:
### 대제목