In [1]:
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# 데이터 프레임의 컬럼 관련
df.columns # 컬럼 리스트

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [ ]:
# df['컬럼이름'] , df[['컬럼이름1','컬럼이름2']] -> 2개 이상이면 리스트형태로 반환
df[['이름','수학']]

       이름   수학
지원번호
1번    강나래  100
2번    강태원   50
3번    강호림   70
4번    김수찬   70
5번    김재욱   10
6번    박동현   95
7번    박혜정   45
8번    승근열   90

In [5]:
# df['이름':'과학']는 불가
df[df.columns[0:4]] # 이것은 가능

       이름    학교    키   국어
지원번호
1번    강나래   신림고  197   90
2번    강태원   신림고  184   40
3번    강호림   신림고  168   80
4번    김수찬   신림고  187   40
5번    김재욱   신림고  188   15
6번    박동현  디지털고  202   80
7번    박혜정  디지털고  188   55
8번    승근열  디지털고  190  100

In [7]:
df.loc[:,'이름':'과학']

       이름    학교    키   국어   영어   수학  과학
지원번호
1번    강나래   신림고  197   90   85  100  95
2번    강태원   신림고  184   40   35   50  55
3번    강호림   신림고  168   80   75   70  80
4번    김수찬   신림고  187   40   60   70  75
5번    김재욱   신림고  188   15   20   10  35
6번    박동현  디지털고  202   80  100   95  85
7번    박혜정  디지털고  188   55   65   45  40
8번    승근열  디지털고  190  100   85   90  95

In [ ]:
# 마지막 컬럼 출력
df[df.columns[-1]]

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [9]:
df[df.columns[[0,3,-1]]]

       이름   국어        SW특기
지원번호
1번    강나래   90      Python
2번    강태원   40        Java
3번    강호림   80  Javascript
4번    김수찬   40         NaN
5번    김재욱   15         NaN
6번    박동현   80           C
7번    박혜정   55      PYTHON
8번    승근열  100          C#

In [ ]:
df[0:3] # index에 해당되는 3개 항목(행) 출력

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [11]:
df.iloc[0:3]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [14]:
# loc 관련 내용 : index 내용으로 출력, 이름으로 출력
df.loc['1번']
df.loc[['1번','2번']] # index 내용 출력
df.loc['1번':'5번']
df.loc['1번','이름':'수학']
df.loc['2번':'5번','이름':'수학']

       이름   학교    키  국어  영어  수학
지원번호
2번    강태원  신림고  184  40  35  50
3번    강호림  신림고  168  80  75  70
4번    김수찬  신림고  187  40  60  70
5번    김재욱  신림고  188  15  20  10

In [13]:
df.iloc[0:3,0:4]

       이름   학교    키  국어
지원번호
1번    강나래  신림고  197  90
2번    강태원  신림고  184  40
3번    강호림  신림고  168  80

In [15]:
df.iloc[0:4]

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript
4번    김수찬  신림고  187  40  60   70  75  80         NaN

In [17]:
df.iloc[[0,1,4]]

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85  Python
2번    강태원  신림고  184  40  35   50  55  25    Java
5번    김재욱  신림고  188  15  20   10  35  10     NaN

In [ ]:
# 조건
# 학생들의 키가 185이상 인지 판별
df['키'] > 185

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [ ]:
# 185학생만 출력하려면
df[df['키']>185]['키']

지원번호
1번    197
4번    187
5번    188
6번    202
7번    188
8번    190
Name: 키, dtype: int64

In [ ]:
# 국어 80점 이상 학생
df[df['국어'] > 80]['국어']

지원번호
1번     90
8번    100
Name: 국어, dtype: int64

In [24]:
df[df['키']>190][['학교','과학']]

        학교  과학
지원번호
1번     신림고  95
6번    디지털고  85

In [25]:
df.loc[df['키']>190,'학교':'수학']

        학교    키  국어   영어   수학
지원번호
1번     신림고  197  90   85  100
6번    디지털고  202  80  100   95

In [26]:
df.loc[(df['키']185) & (df['학교'] =='디지털고')]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3331750838.py, line 1)

In [ ]:
df.loc[()]