In [51]:
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [52]:
# 컬럼 전체 이름변경
# df['학교'] = df['학교']+'등학교'
df.replace({'고':'등학교'},inplace=True)
df['학교'] = df['학교'].str.replace({'고':'고등학교'})
df['학교']

지원번호
1번     신림고등학교
2번     신림고등학교
3번     신림고등학교
4번     신림고등학교
5번     신림고등학교
6번    디지털고등학교
7번    디지털고등학교
8번    디지털고등학교
Name: 학교, dtype: str

In [53]:
# 키 + cm추가
# df['키'] = df['키'] + 'cm' # 오류 남 -> 키의 수는 숫자형, cm는 문자형 -> 다른 형태로 오류남
df['키'] = df['키'] + 100 # 이건 가능(숫자형 + 숫자형)
df

       이름       학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고등학교  297   90   85  100  95  85      Python
2번    강태원   신림고등학교  284   40   35   50  55  25        Java
3번    강호림   신림고등학교  268   80   75   70  80  75  Javascript
4번    김수찬   신림고등학교  287   40   60   70  75  80         NaN
5번    김재욱   신림고등학교  288   15   20   10  35  10         NaN
6번    박동현  디지털고등학교  302   80  100   95  85  80           C
7번    박혜정  디지털고등학교  288   55   65   45  40  35      PYTHON
8번    승근열  디지털고등학교  290  100   85   90  95  95          C#

In [54]:
# 키 + cm추가 하려면, 키를 문자형으로 변환해야 함
df['키'] = df['키'].astype(str)
df.info

<bound method DataFrame.info of        이름       학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고등학교  297   90   85  100  95  85      Python
2번    강태원   신림고등학교  284   40   35   50  55  25        Java
3번    강호림   신림고등학교  268   80   75   70  80  75  Javascript
4번    김수찬   신림고등학교  287   40   60   70  75  80         NaN
5번    김재욱   신림고등학교  288   15   20   10  35  10         NaN
6번    박동현  디지털고등학교  302   80  100   95  85  80           C
7번    박혜정  디지털고등학교  288   55   65   45  40  35      PYTHON
8번    승근열  디지털고등학교  290  100   85   90  95  95          C#>

In [55]:
# df['키'] = df['키'].astype(str) + 'cm'
# df

In [56]:
# 함수 적용 : apply() - 컬럼 전체에 적용
def add_cm(h):
    return str(h)+'센티미터'

df['키'] = df['키'].apply(add_cm)
df

       이름       학교        키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고등학교  297센티미터   90   85  100  95  85      Python
2번    강태원   신림고등학교  284센티미터   40   35   50  55  25        Java
3번    강호림   신림고등학교  268센티미터   80   75   70  80  75  Javascript
4번    김수찬   신림고등학교  287센티미터   40   60   70  75  80         NaN
5번    김재욱   신림고등학교  288센티미터   15   20   10  35  10         NaN
6번    박동현  디지털고등학교  302센티미터   80  100   95  85  80           C
7번    박혜정  디지털고등학교  288센티미터   55   65   45  40  35      PYTHON
8번    승근열  디지털고등학교  290센티미터  100   85   90  95  95          C#

In [57]:
# 함수적용

def capChange(lang):
    pass


# df['SW특기'].str.lower()

def capChange(lang):
    if pd.notnull(lang):
        return lang.lower()
    else:
        return "특기없음"

df['SW특기'] = df['SW특기'].apply(capChange)
df['SW특기']

지원번호
1번        python
2번          java
3번    javascript
4번          특기없음
5번          특기없음
6번             c
7번        python
8번            c#
Name: SW특기, dtype: str

In [58]:
# 문제 : 
# 1.합계 컬럼(과목 총점 계산해서)을 추가하시오.
# 2.평균 컬럼을 추가하시오.
# 3.등급 컬럼을 추가해서 90점 이상 A, 80점 이상 B, 70점 이상 C, 60점 이상 D, 그 외는 F로 입력하시오.
# 3번은 함수를 사용해서 처리

In [59]:
df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
df['평균'] = df['합계'] / 5
df['등급'] = "F"
df

       이름       학교        키   국어   영어   수학  과학  사회        SW특기   합계    평균 등급
지원번호
1번    강나래   신림고등학교  297센티미터   90   85  100  95  85      python  455  91.0  F
2번    강태원   신림고등학교  284센티미터   40   35   50  55  25        java  205  41.0  F
3번    강호림   신림고등학교  268센티미터   80   75   70  80  75  javascript  380  76.0  F
4번    김수찬   신림고등학교  287센티미터   40   60   70  75  80        특기없음  325  65.0  F
5번    김재욱   신림고등학교  288센티미터   15   20   10  35  10        특기없음   90  18.0  F
6번    박동현  디지털고등학교  302센티미터   80  100   95  85  80           c  440  88.0  F
7번    박혜정  디지털고등학교  288센티미터   55   65   45  40  35      python  240  48.0  F
8번    승근열  디지털고등학교  290센티미터  100   85   90  95  95          c#  465  93.0  F

In [60]:

df['평균'] = df['평균'].astype(int)
def grade(평균):
    if 평균 >=90: return "A"
    elif 80<= 평균 < 90: return "B"
    elif 70<= 평균 < 80: return "C"
    elif 60<= 평균 < 70: return "D"
    else: return "F"

df['등급'] = df['평균'].apply(grade)
df

       이름       학교        키   국어   영어   수학  과학  사회        SW특기   합계  평균 등급
지원번호
1번    강나래   신림고등학교  297센티미터   90   85  100  95  85      python  455  91  A
2번    강태원   신림고등학교  284센티미터   40   35   50  55  25        java  205  41  F
3번    강호림   신림고등학교  268센티미터   80   75   70  80  75  javascript  380  76  C
4번    김수찬   신림고등학교  287센티미터   40   60   70  75  80        특기없음  325  65  D
5번    김재욱   신림고등학교  288센티미터   15   20   10  35  10        특기없음   90  18  F
6번    박동현  디지털고등학교  302센티미터   80  100   95  85  80           c  440  88  B
7번    박혜정  디지털고등학교  288센티미터   55   65   45  40  35      python  240  48  F
8번    승근열  디지털고등학교  290센티미터  100   85   90  95  95          c#  465  93  A

In [61]:
# rank 변수
df['합계'].rank() # 합계를 기준으로 등수를 매겨라 -> 낮은 점수가 낮은 숫자로 나타남 -> 높을 수록 높은 등수가 나오려면, ascending = False넣어야 함

지원번호
1번    7.0
2번    2.0
3번    5.0
4번    4.0
5번    1.0
6번    6.0
7번    3.0
8번    8.0
Name: 합계, dtype: float64

In [62]:
df['등수'] = df['합계'].rank(ascending=False).astype(int)
df

       이름       학교        키   국어   영어   수학  과학  사회        SW특기   합계  평균 등급  등수
지원번호
1번    강나래   신림고등학교  297센티미터   90   85  100  95  85      python  455  91  A   2
2번    강태원   신림고등학교  284센티미터   40   35   50  55  25        java  205  41  F   7
3번    강호림   신림고등학교  268센티미터   80   75   70  80  75  javascript  380  76  C   4
4번    김수찬   신림고등학교  287센티미터   40   60   70  75  80        특기없음  325  65  D   5
5번    김재욱   신림고등학교  288센티미터   15   20   10  35  10        특기없음   90  18  F   8
6번    박동현  디지털고등학교  302센티미터   80  100   95  85  80           c  440  88  B   3
7번    박혜정  디지털고등학교  288센티미터   55   65   45  40  35      python  240  48  F   6
8번    승근열  디지털고등학교  290센티미터  100   85   90  95  95          c#  465  93  A   1

In [63]:
# 만약, 동점자가 있다면..
df = pd.read_excel('file/students.xlsx',index_col="번호")
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [64]:
# 합계, 평균만 가져온다.
# df[['합계','평균']]

In [65]:
df.sort_values("합계",ascending=False).head(30)

KeyError: '합계'

In [66]:
df['등수'] = df['합계'].rank(ascending=False).astype(int)

KeyError: '합계'

In [ ]:
# method = 'min'-> 1,2,2,4 / method = 'dense' -> 1,2,2,3 # default는 min으로 되어 있음.