In [27]:
import pandas as pd
df = pd.read_excel("file/students.xlsx",index_col="번호")
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [28]:
df.columns
# 국어,영어,수학,과학,사회 합계 컬럼을 추가하고 합계점수가 350점 이상만 출력하시오.
# 350점 미만 삭제 후 출력

Index(['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기'], dtype='str')

In [29]:
df['합계'] = df['국어'] + df['영어'] + df['수학']
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund   신림고   2  171  56  92  60       c  208
2       Kirbee   구로고   1  199  53  10  45       C  108
3    Appolonia   구로고   3  193  77  52  81       C  210
4        Avery   구로고   2  187  59  35  43       C  137
5       Dallis  디지털고   1  209  97  57  76       C  230
..         ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213
97        Nada   구로고   3  170  60  89  55  PYTHON  204
98       Fiona   신림고   1  200  97  95  84       C  276
99        Leif   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 9 columns]

In [30]:
filt = df['합계']>=350
df[filt]

Empty DataFrame
Columns: [이름, 학교, 학년, 키, 국어, 영어, 수학, SW특기, 합계]
Index: []

In [31]:
# 1.index추가 : loc[] 이용, 컬럼 개수만큼 입력
# df.loc['9번'] = ['홍길동', '구로고', 190, 90, 80, 70, 60, 50,'Python']

# 2.SW특기 부분 값 추가
# df.loc['4번','SW특기'] = 'C' # index, 컬럼 지정해서 값 입력

# 3. 부분 학교,SW특기 컬럼에 값 수정
# df.loc['4번',['학교','SW특기']] = ['디지털고','python']
# df.loc['5번',['학교','사회','SW특기']] = ['디지털고',50,'Java']

In [33]:
# # index 추가 : lof[] 이용, 컬럼 갯수만큼 입력


# df.loc['9번'] = ['홍길동','구로고',90,80,70,60,50,'Python']
# df

In [34]:
# df.loc['4번','SW특기'] = 'C' # index, 컬럼 지정해서 값 입력
# 학교, SW특기 컬럼에 값 추가
df.loc['4번',['학교','SW특기']]=['디지털고','Python']

df.loc[5,['학교','사회','SW특기']] = ['디지털고',50,'Java'] # 5행을 찾아서 학교, 사회, SW특기 컬럼열의 숫자를 우측으로 고쳐라
df

            이름    학교   학년      키    국어    영어    수학    SW특기     합계    사회
번호
1      Eadmund   신림고  2.0  171.0  56.0  92.0  60.0       c  208.0   NaN
2       Kirbee   구로고  1.0  199.0  53.0  10.0  45.0       C  108.0   NaN
3    Appolonia   구로고  3.0  193.0  77.0  52.0  81.0       C  210.0   NaN
4        Avery   구로고  2.0  187.0  59.0  35.0  43.0       C  137.0   NaN
5       Dallis  디지털고  1.0  209.0  97.0  57.0  76.0    Java  230.0  50.0
..         ...   ...  ...    ...   ...   ...   ...     ...    ...   ...
97        Nada   구로고  3.0  170.0  60.0  89.0  55.0  PYTHON  204.0   NaN
98       Fiona   신림고  1.0  200.0  97.0  95.0  84.0       C  276.0   NaN
99        Leif   구로고  2.0  192.0  96.0  84.0  34.0  PYTHON  214.0   NaN
100   Jonathan  디지털고  2.0  195.0  84.0  63.0  80.0    JAVA  227.0   NaN
4번         NaN  디지털고  NaN    NaN   NaN   NaN   NaN  Python    NaN   NaN

[101 rows x 10 columns]