In [10]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# 합계 컬럼 추가
# SW특가 있으면 합계점수를 추가해서 입력하시오. NaN은 ()로 표시함

df['합계'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python  455
2번    강태원   신림고  184   40   35   50  55  25        Java  205
3번    강호림   신림고  168   80   75   70  80  75  Javascript  380
4번    김수찬   신림고  187   40   60   70  75  80         NaN  325
5번    김재욱   신림고  188   15   20   10  35  10         NaN   90
6번    박동현  디지털고  202   80  100   95  85  80           C  440
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240
8번    승근열  디지털고  190  100   85   90  95  95          C#  465

In [ ]:
# 함수를 이용하지 않고 합산

# df.loc[df['SW특기'].notna(), '합계'] += 10
# df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python  475
2번    강태원   신림고  184   40   35   50  55  25        Java  225
3번    강호림   신림고  168   80   75   70  80  75  Javascript  400
4번    김수찬   신림고  187   40   60   70  75  80         NaN  325
5번    김재욱   신림고  188   15   20   10  35  10         NaN   90
6번    박동현  디지털고  202   80  100   95  85  80           C  460
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  260
8번    승근열  디지털고  190  100   85   90  95  95          C#  485

In [ ]:
# # 함수를 이용한 합산

# def cal_sw(df2):
#     if df2['SW특기'] != '':
#         return df2['합계']+5
#     else:
#         return df2['합계']

# df['합계'] = df.apply(cal_sw,axis=1)
# str.zfill() : 0으로 채워줌