In [1]:
import pandas as pd
df = pd.read_excel("file/students.xlsx",index_col="번호")
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [2]:
df.columns
# 국어,영어,수학,과학,사회 합계 컬럼을 추가하고 합계점수가 350점 이상만 출력하시오.
# 350점 미만 삭제 후 출력

Index(['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기'], dtype='str')

In [3]:
df['합계'] = df['국어'] + df['영어'] + df['수학']
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund   신림고   2  171  56  92  60       c  208
2       Kirbee   구로고   1  199  53  10  45       C  108
3    Appolonia   구로고   3  193  77  52  81       C  210
4        Avery   구로고   2  187  59  35  43       C  137
5       Dallis  디지털고   1  209  97  57  76       C  230
..         ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213
97        Nada   구로고   3  170  60  89  55  PYTHON  204
98       Fiona   신림고   1  200  97  95  84       C  276
99        Leif   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 9 columns]

In [6]:
filt = df['합계']>=250
df[filt]

        이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
34  Nollie  디지털고   1  197  84  89  78       C  251
39     Ban   구로고   1  185  82  94  80  Python  256
77   Lorna   신림고   1  208  99  98  86  Python  283
98   Fiona   신림고   1  200  97  95  84       C  276

In [52]:
# 1.index추가 : loc[] 이용, 컬럼 개수만큼 입력
# df.loc['9번'] = ['홍길동', '구로고', 190, 90, 80, 70, 60, 50,'Python']

# 2.SW특기 부분 값 추가
# df.loc['4번','SW특기'] = 'C' # index, 컬럼 지정해서 값 입력

# 3. 부분 학교,SW특기 컬럼에 값 수정
# df.loc['4번',['학교','SW특기']] = ['디지털고','python']
# df.loc['5번',['학교','사회','SW특기']] = ['디지털고',50,'Java']

In [53]:
# # index 추가 : lof[] 이용, 컬럼 갯수만큼 입력


# df.loc['9번'] = ['홍길동','구로고',90,80,70,60,50,'Python']
# df

In [54]:
# df.loc['4번','SW특기'] = 'C' # index, 컬럼 지정해서 값 입력
# 학교, SW특기 컬럼에 값 추가
df.loc[4,['학교','SW특기']]=['디지털고','Python']

df.loc[5,['학교','사회','SW특기']] = ['디지털고',50,'Java'] # 5행을 찾아서 학교, 사회, SW특기 컬럼열의 숫자를 우측으로 고쳐라
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계    사회
번호
1      Eadmund   신림고   2  171  56  92  60       c  208   NaN
2       Kirbee   구로고   1  199  53  10  45       C  108   NaN
3    Appolonia   구로고   3  193  77  52  81       C  210   NaN
4        Avery  디지털고   2  187  59  35  43  Python  137   NaN
5       Dallis  디지털고   1  209  97  57  76    Java  230  50.0
..         ...   ...  ..  ...  ..  ..  ..     ...  ...   ...
96        Luke   신림고   3  187  91  63  59  Python  213   NaN
97        Nada   구로고   3  170  60  89  55  PYTHON  204   NaN
98       Fiona   신림고   1  200  97  95  84       C  276   NaN
99        Leif   구로고   2  192  96  84  34  PYTHON  214   NaN
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227   NaN

[100 rows x 10 columns]

In [56]:
df.loc[4,'이름']

'Avery'

In [57]:
df['체육'] = 100
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계    사회   체육
번호
1      Eadmund   신림고   2  171  56  92  60       c  208   NaN  100
2       Kirbee   구로고   1  199  53  10  45       C  108   NaN  100
3    Appolonia   구로고   3  193  77  52  81       C  210   NaN  100
4        Avery  디지털고   2  187  59  35  43  Python  137   NaN  100
5       Dallis  디지털고   1  209  97  57  76    Java  230  50.0  100
..         ...   ...  ..  ...  ..  ..  ..     ...  ...   ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213   NaN  100
97        Nada   구로고   3  170  60  89  55  PYTHON  204   NaN  100
98       Fiona   신림고   1  200  97  95  84       C  276   NaN  100
99        Leif   구로고   2  192  96  84  34  PYTHON  214   NaN  100
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227   NaN  100

[100 rows x 11 columns]

In [58]:
df.columns

Index(['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계', '사회', '체육'], dtype='str')

In [59]:
# 컬럼 이름 변경 -> 변경할 위치에 컬럼명을 입력하면 됨

df2 = df[['이름','국어','영어']]
df2.columns = ['name','kor','eng'] # 컬럼명 변경

In [ ]:
# 부분적으로 컬럼명 변경할 경우, rename
df.rename(columns={'이름':'name','국어':'kor','영어':'eng','수학':'math'},inplace=True)
df

          name    학교  학년    키  kor  eng  math    SW특기   합계    사회   체육
번호
1      Eadmund   신림고   2  171   56   92    60       c  208   NaN  100
2       Kirbee   구로고   1  199   53   10    45       C  108   NaN  100
3    Appolonia   구로고   3  193   77   52    81       C  210   NaN  100
4        Avery  디지털고   2  187   59   35    43  Python  137   NaN  100
5       Dallis  디지털고   1  209   97   57    76    Java  230  50.0  100
..         ...   ...  ..  ...  ...  ...   ...     ...  ...   ...  ...
96        Luke   신림고   3  187   91   63    59  Python  213   NaN  100
97        Nada   구로고   3  170   60   89    55  PYTHON  204   NaN  100
98       Fiona   신림고   1  200   97   95    84       C  276   NaN  100
99        Leif   구로고   2  192   96   84    34  PYTHON  214   NaN  100
100   Jonathan  디지털고   2  195   84   63    80    JAVA  227   NaN  100

[100 rows x 11 columns]

In [ ]:
# df.columns[1] = "학교" # 이런 형태는 안됨 -> rename으로 해야 됨