In [21]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [22]:
# 부류별 그룹핑 groupby : size, mean, sum, max, min
df.groupby('학교').get_group('디지털고') # 학교를 기준으로 그룹핑해서 디지털고에 대당하는 것을 출력하라
df.groupby('학교').size() # 학교를 기준으로 그룹핑해서 각각의 크기를 알려줌
df.groupby('학교').size()['디지털고'] # 학교를 기준으로 그룹핑해서 디지털고 크기를 알려줌
# df['학교'].unique()
df.groupby('학교')['키'].mean() # 학교기준으로 학교별 키 평균
# df.groupby('학교').mean() # 학교 전체는 안나옴
df.groupby('학교')['국어'].mean()
df.groupby('학교')[['국어','영어','수학']].mean()
df.groupby('학교')[['국어','영어','수학']].sum()
df.groupby('학교')[['국어','영어','수학']].max()

       국어   영어   수학
학교
디지털고  100  100   95
신림고    90   85  100

In [23]:
df.groupby('학교').size() # 위, 아래는 완전히 같은 명령문임
df['학교'].value_counts

<bound method IndexOpsMixin.value_counts of 지원번호
1번     신림고
2번     신림고
3번     신림고
4번     신림고
5번     신림고
6번    디지털고
7번    디지털고
8번    디지털고
Name: 학교, dtype: str>

In [24]:
df['학년'] = [3,3,2,1,1,3,2,2]
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기  학년
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python   3
2번    강태원   신림고  184   40   35   50  55  25        Java   3
3번    강호림   신림고  168   80   75   70  80  75  Javascript   2
4번    김수찬   신림고  187   40   60   70  75  80         NaN   1
5번    김재욱   신림고  188   15   20   10  35  10         NaN   1
6번    박동현  디지털고  202   80  100   95  85  80           C   3
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON   2
8번    승근열  디지털고  190  100   85   90  95  95          C#   2

In [26]:
# df.groupby('학교')['학년'].value_counts().loc['구로고']
df.groupby('학교')['학년'].value_counts().loc['디지털고']
df.groupby('학교')['학년'].value_counts()

학교    학년
디지털고  2     2
      3     1
신림고   3     2
      1     2
      2     1
Name: count, dtype: int64

In [28]:
df.groupby('학교')['학년'].value_counts(normalize=True).loc['디지털고'] # normalize는 백분율화함

학년
2    0.666667
3    0.333333
Name: proportion, dtype: float64

In [33]:
df.groupby('학년')['키'].mean()
df.groupby('학년')['키'].mean().sort_values()

학년
2    182.000000
1    187.500000
3    194.333333
Name: 키, dtype: float64

In [34]:
df.groupby('학년')[['국어','영어']].mean()
df.groupby('학년')[['국어','영어']].sum().sort_values('국어') # 두개의 요소가 있으면, 어떤 기준으로 정렬할 것인지 표시해야 함
df.groupby('학교')[['국어','영어']].count().sort_values('영어')

      국어  영어
학교
디지털고   3   3
신림고    5   5

In [36]:
df = pd.read_csv('file/drinks.csv')
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [43]:
# 대륙별 규모를 알고 싶으면
df.groupby('continent').size()
df.groupby('continent').size().sort_values(ascending=False) # 자료를 정렬까지 가능(ascending=False 넣으면 역순 정렬)

continent
AF    53
EU    45
AS    44
OC    16
SA    12
dtype: int64

In [45]:
# 대륙별 퍼센트를 출력하시오.
str((df['continent'].value_counts(normalize=True)*100).astype(int))
# df.groupby('continent').value_counts(normalize=True)

'continent\nAF    31\nEU    26\nAS    25\nOC     9\nSA     7\nName: proportion, dtype: int64'