In [44]:
import pandas as pd
df = pd.read_excel("file/students.xlsx",index_col="번호")
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [45]:
# 합계, 평균, 결과 컬럼을 추가
# 결과는 평균 점수가 70점 이상이면 합격, 미만은 불합격으로 출력, 합격과 불합격 빈도도 출력

In [46]:
df['합계'] = df['국어'] + df['영어'] + df['수학']
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund   신림고   2  171  56  92  60       c  208
2       Kirbee   구로고   1  199  53  10  45       C  108
3    Appolonia   구로고   3  193  77  52  81       C  210
4        Avery   구로고   2  187  59  35  43       C  137
5       Dallis  디지털고   1  209  97  57  76       C  230
..         ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213
97        Nada   구로고   3  170  60  89  55  PYTHON  204
98       Fiona   신림고   1  200  97  95  84       C  276
99        Leif   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 9 columns]

In [47]:
df['평균'] = (df['국어'] + df['영어'] + df['수학'])/3
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000
4        Avery   구로고   2  187  59  35  43       C  137  45.666667
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667

[100 rows x 10 columns]

In [48]:
df['결과'] = "불합격"
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000  불합격
4        Avery   구로고   2  187  59  35  43       C  137  45.666667  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667  불합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000  불합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000  불합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333  불합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667  불합격

[100 rows x 11 columns]

In [49]:
df.loc[df['평균']>=70,'결과'] = "합격"
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000   합격
4        Avery   구로고   2  187  59  35  43       C  137  45.666667  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667   합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000   합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000   합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333   합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667   합격

[100 rows x 11 columns]

In [50]:
# 결과 컬럼에 대해서 각 그룹별 빈도수 확인 가능

df.value_counts('결과')

결과
불합격    72
합격     28
Name: count, dtype: int64

In [51]:
df2 = df[['이름','평균','결과']]
df2

            이름         평균   결과
번호
1      Eadmund  69.333333  불합격
2       Kirbee  36.000000  불합격
3    Appolonia  70.000000   합격
4        Avery  45.666667  불합격
5       Dallis  76.666667   합격
..         ...        ...  ...
96        Luke  71.000000   합격
97        Nada  68.000000  불합격
98       Fiona  92.000000   합격
99        Leif  71.333333   합격
100   Jonathan  75.666667   합격

[100 rows x 3 columns]

In [52]:
# 결과를 이름 뒤로 가져오려면.. 


df[['이름','결과','국어','영어','수학']]  # 컬럼명을 직접 입력해도 되나, 컬럼이 많으면 컬럼을 조회해서 붙여 넣으면 편함

            이름   결과  국어  영어  수학
번호
1      Eadmund  불합격  56  92  60
2       Kirbee  불합격  53  10  45
3    Appolonia   합격  77  52  81
4        Avery  불합격  59  35  43
5       Dallis   합격  97  57  76
..         ...  ...  ..  ..  ..
96        Luke   합격  91  63  59
97        Nada  불합격  60  89  55
98       Fiona   합격  97  95  84
99        Leif   합격  96  84  34
100   Jonathan   합격  84  63  80

[100 rows x 5 columns]

In [53]:
# 컬럼 순서 변경 : 
cols = list(df.columns)
cols

['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계', '평균', '결과']

In [54]:
a_list = [1,2,3]
b_list = [4,5,6]
c = a_list + b_list
c

[1, 2, 3, 4, 5, 6]

In [55]:
# cols 리스트 순서 변경

# 평균, 결과 컬럼명 출력
cols[-2:]

['평균', '결과']

In [56]:
# 이름~합계까지 컬럼명 출력

cols[1:-2]

['학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']

In [57]:
cols[0]

'이름'

In [58]:
type(cols[0]) # str 
type(cols[1:-2]) # list

list

In [59]:
# cols[0]+cols[1:-2]+cols[-2:] # 에러 남 - 형태가 다름

[cols[0]]+cols[-2:]+cols[1:-2]

['이름', '평균', '결과', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']

In [60]:
df = df[cols]
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000   합격
4        Avery   구로고   2  187  59  35  43       C  137  45.666667  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667   합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000   합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000   합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333   합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667   합격

[100 rows x 11 columns]

In [61]:
# # [col 리스트 순서를 변경]

# # 1.리스트 타입으로 변경 후 순서를 변경
# cols = list(df.columns)

# # cols

In [62]:
# 컬럼 수정 - replace, 존재하는 컬럼에 값을 입력하면 수정됨
# 컬럼 추가 - 없는 컬럼에 값을 입력하면 추가됨
# 컬럼 삭제 - drop : 여러개 삭제 가능, inplace=True

In [63]:
# row : index 수정, 추가, 삭제
# index 삭제 : 조건 사용해서 삭제
df.loc[df['평균'] >= 70, '결과'] = "합격"

In [64]:
filt = df['수학'] > 80
df[filt] # 80점 이상인 학생만 나옴
df[filt].count # 80점 이상인 학생 수가 나옴

<bound method DataFrame.count of             이름    학교  학년    키  국어  영어  수학        SW특기   합계         평균   결과
번호
3    Appolonia   구로고   3  193  77  52  81           C  210  70.000000   합격
7         Gaye   신림고   3  192  65  27  86      PYTHON  178  59.333333  불합격
11        Mora  디지털고   1  166  74  29  89              192  64.000000  불합격
21   Evangelia   신림고   2  190  51  71  83      PYTHON  205  68.333333  불합격
22        Abbe   구로고   1  188  72  65  86           c  223  74.333333   합격
25       Robin   구로고   2  187  64  44  89      PYTHON  197  65.666667  불합격
27      Gordan  디지털고   1  183  90  31  90      PYTHON  211  70.333333   합격
31      Holmes   구로고   1  184  51  21  87      Python  159  53.000000  불합격
36     Ainslee  디지털고   2  201  66  15  89  Javascript  170  56.666667  불합격
40       Aimil  디지털고   2  207  65  14  86      Python  165  55.000000  불합격
46         Nat  디지털고   2  171  70  38  82  Javascript  190  63.333333  불합격
54         Ula   신림고   3  168  80  59  85        java  224  74.666667   합격
55    Emmanuel   구로고   2  191  63  27  83        JAVA  173  57.666667  불합격
61        Gage   신림고   3  189  58  13  83              154  51.333333  불합격
66      Joanie   신림고   1  200  75  24  85        java  184  61.333333  불합격
70       Gilda   구로고   3  189  71  43  89      Python  203  67.666667  불합격
77       Lorna   신림고   1  208  99  98  86      Python  283  94.333333   합격
85     Diahann   신림고   3  189  90  26  83      PYTHON  199  66.333333  불합격
95  Clementine   신림고   1  194  71  13  81        JAVA  165  55.000000  불합격
98       Fiona   신림고   1  200  97  95  84           C  276  92.000000   합격>

In [65]:
df.drop(columns=['평균','결과'],inplace=True)
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund   신림고   2  171  56  92  60       c  208
2       Kirbee   구로고   1  199  53  10  45       C  108
3    Appolonia   구로고   3  193  77  52  81       C  210
4        Avery   구로고   2  187  59  35  43       C  137
5       Dallis  디지털고   1  209  97  57  76       C  230
..         ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213
97        Nada   구로고   3  170  60  89  55  PYTHON  204
98       Fiona   신림고   1  200  97  95  84       C  276
99        Leif   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 9 columns]

In [ ]:
# df.drop(index=['평균','결과'],inplace=True)
# df.drop(index=['1번','2번'],inplace=True)

In [66]:
filt = df['수학']>=80