In [3]:
import pandas as pd
df = pd.read_excel("file/score.xlsx")
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기
0   1번  강나래   신림고  197   90   85  100  95  85      Python
1   2번  강태원   신림고  184   40   35   50  55  25        Java
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN
5   6번  박동현  디지털고  202   80  100   95  85  80           C
6   7번  박혜정  디지털고  188   55   65   45  40  35      PYTHON
7   8번  승근열  디지털고  190  100   85   90  95  95          C#

In [30]:
df.replace({'구로고':'신림고'},inplace=True)

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
0   1번  강나래   신림고  197   90   85  100  95  85      Python  455   합격
1   2번  강태원   신림고  184   40   35   50  55  25        Java  205  NaN
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript  380  NaN
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN  325  NaN
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN   90  NaN
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C  440   합격
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON  240  NaN
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#  465   합격

In [31]:
df.replace({'구로고':'신림고','디지털고':'포켓몬고'},inplace=True)

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
0   1번  강나래   신림고  197   90   85  100  95  85      Python  455   합격
1   2번  강태원   신림고  184   40   35   50  55  25        Java  205  NaN
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript  380  NaN
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN  325  NaN
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN   90  NaN
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C  440   합격
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON  240  NaN
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#  465   합격

In [45]:
# 컬럼 추가 : 없는 컬럼이름과 값을 입력하면, 컬럼이 추가됨


df['결과'] = 0
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기  결과
0   1번  강나래   신림고  197   90   85  100  95  85      Python   0
1   2번  강태원   신림고  184   40   35   50  55  25        Java   0
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript   0
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN   0
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN   0
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C   0
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON   0
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#   0

In [46]:
# 컬럼 값의 수정 : replace로 변경해도 되고, 있는 컬럼에 값을 입력하면 수정됨


df['결과'] = "불합격"
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기   결과
0   1번  강나래   신림고  197   90   85  100  95  85      Python  불합격
1   2번  강태원   신림고  184   40   35   50  55  25        Java  불합격
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript  불합격
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN  불합격
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN  불합격
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C  불합격
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON  불합격
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#  불합격

In [47]:
# 합계를 추가하려면..

df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기   결과   합계
0   1번  강나래   신림고  197   90   85  100  95  85      Python  불합격  455
1   2번  강태원   신림고  184   40   35   50  55  25        Java  불합격  205
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript  불합격  380
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN  불합격  325
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN  불합격   90
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C  불합격  440
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON  불합격  240
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#  불합격  465

In [48]:
# 조건으로 컬럼 수정 - 조건에 맞는 컬럼의 값을 변경할 수 있음
# 컬럼에서 전체 수정은 replace, 일부만 수정은 loc
# 합계가 400이상인 경우

In [49]:
# [ 1.글자수정 - replace() ]
# columns 수정 - replace()를 이용하여 컬럼의 값을 변경할 수 있음.
# df.replace({'구로고': '신림고'}, inplace=True)  # 학교이름변경
# df['학교'] = df['학교'].replace({'구로고': '신림고','디지털고':'포켓몬고'} )  # 학교이름변경
# df.replace({'구로고': '신림고','디지털고':'포켓몬고'},inplace=True )  # 학교이름변경
#--------------------------
# [ 2.컬럼전체수정 - 컬럼에 값을 입력 ]
# 존재하는 column에 값을 입력하면 수정이 됨.
#  예) df['합계']가 존재할때, 다시 값을 입력하면 수정이 됨. df['합계'] = 1
#--------------------------
# [ 3.부분수정 - loc ]
# 조건으로 컬럼 수정 - 조건에 맞는 컬럼의 값을 변경할 수 있음.
# df.loc[df['합계']>400, '결과'] = '합격'
#--------------------------
# columns 추가 - 없는 컬럼을 입력하면 추가가 됨.
# df['결과'] = 0
# df['결과'] = "불합격"
# df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']

In [50]:
# iloc로 실행 -> 위치값을 입력 -> 확인 필요

# df.iloc[df['합계']>400,10] = '합격'
# df

In [51]:
# iloc[row_index, column_index] -> 특정 위치의 데이터 선택
df.iloc[4,10]

'불합격'

In [52]:
df.loc[df['합계']>400,'결과'] = "합격"
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기   결과   합계
0   1번  강나래   신림고  197   90   85  100  95  85      Python   합격  455
1   2번  강태원   신림고  184   40   35   50  55  25        Java  불합격  205
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript  불합격  380
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN  불합격  325
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN  불합격   90
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C   합격  440
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON  불합격  240
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#   합격  465

In [53]:
# 컬럼 삭제 : drop으로 삭제, del로 삭제 모두 가능

# # df.drop(columns=['결과'],inplace=True) # inplace를 서야 함
# df.drop(columns=["결과","합계"],inplace=True) # 2개 컬럼 동시 삭제
del df['결과']
df

  지원번호   이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
0   1번  강나래   신림고  197   90   85  100  95  85      Python  455
1   2번  강태원   신림고  184   40   35   50  55  25        Java  205
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript  380
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN  325
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN   90
5   6번  박동현  포켓몬고  202   80  100   95  85  80           C  440
6   7번  박혜정  포켓몬고  188   55   65   45  40  35      PYTHON  240
7   8번  승근열  포켓몬고  190  100   85   90  95  95          C#  465