In [1]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

In [2]:
# 관객수가 가장 많은 상위 5개만 출력
# 관객수 천단위 출력, ',' 붙일 것
# 관객수 끝에 만명을 붙일 것

In [3]:
df = pd.DataFrame(data)
df

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [4]:
df1 = df.sort_values('관객 수',ascending=False)
df[:5]

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62

In [7]:
df['관객 수'] = df['관객 수'].astype(int)
df['관객 수'] = df['관객 수']*10
# df['관객 수']
# df['관객 수'] = df['관객 수'].astype(str)+'만명'
# ","join.df

ValueError: invalid literal for int() with base 10: '17610만명'

In [6]:
df['관객 수'] = df['관객 수'].map('{:,}.format')
df

TypeError: 'str' object is not callable

In [8]:
# lambda험수 적용

In [9]:
def cal(x):
    return x+2

# (lambda x:x+2) 이렇게 표현 가능(1줄 함수)

In [ ]:
# 1. 함수사용 - 천단위 표시
def cal_change(x):
    return  f"{x:,}"
    # return  '{:,d}'.format() # 숫자를 문자변형

df['관객 수'] = df['관객 수'].apply(cal_change)

#  2. lambda함수적용
df['관객 수'] = df['관객 수'].apply(lambda x: f"{x:,}")

#  3. map사용
# df['관객 수'] = df['관객 수'].map('{:,}'.format)

In [9]:
import pandas as pd
data = {
    
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
df

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [ ]:
# 1)개봉연도 내림차순, 오름차순으로 출력하시오.
# 2)평점이 9점 이상만 출력
# 3)평점 컬럼 내용에 점을 넣어서 출력하시오.
# 4)평점 중에 평점이 평균 이상인 row만 출력하시오.
# 5)2015년 이후에 개봉한 영화를 출력하시오.

In [ ]:
# 1)
df.sort_values("개봉 연도", inplace=True, ascending=False)
df.sort_values("개봉 연도", inplace=True, ascending=True)
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 4 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 320.0 bytes

In [ ]:
# 2)
df.loc[df['평점']>=9.0]

     영화  개봉 연도  관객 수    평점
3  국제시장   2014  1426  9.16
7    암살   2015  1270  9.10
1  극한직업   2019  1626  9.20

In [ ]:
# 4)
df['평점'].mean()
df[df['평점']>=df['평점'].mean()]

        영화  개봉 연도  관객 수    평점
6  7번방의 선물   2013  1281  8.83
0       명량   2014  1761  8.88
3     국제시장   2014  1426  9.16
7       암살   2015  1270  9.10
1     극한직업   2019  1626  9.20

In [ ]:
# 3)
df['평점'].astype(str)+'점'

4    8.62점
5    7.64점
6    8.83점
0    8.88점
3    9.16점
7     9.1점
2    8.73점
1     9.2점
Name: 평점, dtype: str

In [ ]:
# 5)
df['개봉 연도'].astype(int)
df[df['개봉 연도']>=2015]

          영화  개봉 연도  관객 수    평점
7         암살   2015  1270  9.10
2  신과함께-죄와 벌   2017  1441  8.73
1       극한직업   2019  1626  9.20