In [33]:
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
import random

for i in range(8):
    df.iloc[i,9] = random.randint(0,5)
    
    list = [0,1,2,3,4,5,6]
a_arr = random.sample(list,k=8)
a_arr = random.randint(0,6)
a_arr
# df.shape
df['요일'] = a_arr

In [ ]:
# # SW특기 있으면 10점 가산
# df.loc[df['SW특기'].notna(),'합계'] += 10
# df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python  465
2번    강태원   신림고  184   40   35   50  55  25        Java  215
3번    강호림   신림고  168   80   75   70  80  75  Javascript  390
4번    김수찬   신림고  187   40   60   70  75  80         NaN  325
5번    김재욱   신림고  188   15   20   10  35  10         NaN   90
6번    박동현  디지털고  202   80  100   95  85  80           C  450
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  250
8번    승근열  디지털고  190  100   85   90  95  95          C#  475

In [16]:
df.drop(columns=['키'],inplace=True)
df

            이름    학교  학년  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  56  92  60       c
2       Kirbee   구로고   1  53  10  45       C
3    Appolonia   구로고   3  77  52  81       C
4        Avery   구로고   2  59  35  43       C
5       Dallis  디지털고   1  97  57  76       C
..         ...   ...  ..  ..  ..  ..     ...
96        Luke   신림고   3  91  63  59  Python
97        Nada   구로고   3  60  89  55  PYTHON
98       Fiona   신림고   1  97  95  84       C
99        Leif   구로고   2  96  84  34  PYTHON
100   Jonathan  디지털고   2  84  63  80    JAVA

[100 rows x 7 columns]

In [17]:
df.loc[3,'국어']

np.int64(77)

In [21]:
# 컬럼명 변경
df1 = df[['국어', '영어', '수학']]
df1.columns = ['kor','eng','math']
df

            이름    학교  학년  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  56  92  60       c
2       Kirbee   구로고   1  53  10  45       C
3    Appolonia   구로고   3  77  52  81       C
4        Avery   구로고   2  59  35  43       C
5       Dallis  디지털고   1  97  57  76       C
..         ...   ...  ..  ..  ..  ..     ...
96        Luke   신림고   3  91  63  59  Python
97        Nada   구로고   3  60  89  55  PYTHON
98       Fiona   신림고   1  97  95  84       C
99        Leif   구로고   2  96  84  34  PYTHON
100   Jonathan  디지털고   2  84  63  80    JAVA

[100 rows x 7 columns]

In [23]:
df.rename(columns={'국어':'kor','영어':'eng','수학':'math'},inplace=True)
df

            이름    학교  학년  kor  eng  math    SW특기
번호
1      Eadmund   신림고   2   56   92    60       c
2       Kirbee   구로고   1   53   10    45       C
3    Appolonia   구로고   3   77   52    81       C
4        Avery   구로고   2   59   35    43       C
5       Dallis  디지털고   1   97   57    76       C
..         ...   ...  ..  ...  ...   ...     ...
96        Luke   신림고   3   91   63    59  Python
97        Nada   구로고   3   60   89    55  PYTHON
98       Fiona   신림고   1   97   95    84       C
99        Leif   구로고   2   96   84    34  PYTHON
100   Jonathan  디지털고   2   84   63    80    JAVA

[100 rows x 7 columns]