In [38]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import requests
from bs4 import BeautifulSoup
import time
import os
import pandas as pd
import numpy as np
from selenium.webdriver.chrome.options import Options

In [39]:
data = []
data.append({
    '숙소명':'힐튼 경주',
    '평점':9.4,
    '평가수':'10,361',
    '금액':'202,400'
})
data.append({
    '숙소명':'오소한옥스테이',
    '평점':9.8,
    '평가수':'154',
    '금액':'325,000'
})
data.append({
    '숙소명':'소노캄 경주',
    '평점':8.8,
    '평가수':'872',
    '금액':'368,000'
})

In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.DataFrame(data)
df

       숙소명   평점     평가수       금액
0    힐튼 경주  9.4  10,361  202,400
1  오소한옥스테이  9.8     154  325,000
2   소노캄 경주  8.8     872  368,000

In [42]:
df.to_excel("file/yeogi.xlsx")
df

       숙소명   평점     평가수       금액
0    힐튼 경주  9.4  10,361  202,400
1  오소한옥스테이  9.8     154  325,000
2   소노캄 경주  8.8     872  368,000

In [48]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import requests
from bs4 import BeautifulSoup
import time
import os
import pandas as pd
import numpy as np
from selenium.webdriver.chrome.options import Options

In [ ]:
# 2. selenium : 자동화 도구

url = "https://www.yeogi.com/domestic-accommodations?keyword=%EA%B2%BD%EC%A3%BC&checkIn=2026-10-08&checkOut=2026-10-09&personal=2"
options = Options()
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option("useAutomationExtension", False)
options.add_argument("--disable-blink-features=AutomationControlled")

browser = webdriver.Chrome(options=options)
browser.get(url) # 주석 해제하여 사이트 접속
time.sleep(3)
# # 브라우저 열기
browser.get(url)
time.sleep(4)

# prev_height = browser.execute_script("return document.body.scrollHeight")

# while True:
#     # 스크롤 높이 출력
#     print('높이 : ',prev_height)
#     # 스크롤 내리기
#     browser.execute_script("window.scrollTo(0,document.body.scrollHeight)")
#     time.sleep(2)
#     # 스크롤이 추가 되었는지 확인
#     next_height = browser.execute_script("return document.body.scrollHeight")
#     if prev_height == next_height:
#         break
#     prev_height = next_height

# # 파일저장
# soup = BeautifulSoup(browser.page_source,'lxml')
# with open('yeogi.html','w',encoding='utf-8') as f:
#     f.write(soup.prettify())

# # 파일 BeautifulSoup변환
# with open('yeogi.html','r',encoding='utf-8') as f:
#     soup = BeautifulSoup(f,'lxml')

# p_name = []
# p_eval = []
# p_price = []
# uls = soup.find("ul",{"class":"css-y5z6rw"})
# lis = uls.find_all("li")
# for i, li in enumerate(lis):
#     try:
#         p_n = li.find('h3',{"class":"gc-thumbnail-type-seller-card-title css-1gsfgy5"}).get_text().strip()
#         p_e = li.find('span',{"class":"css-ry30z7"}).get_text().strip()
#         p_p = li.find("span",{"class":"css-1nbwqyy"}).get_text().strip()
#         p_name.append(p_n)
#         p_eval.append(p_e)
#         p_price.append(p_p)

#         print(f"{p_n}, {p_e}, {p_p}")
#     except: pass

높이 :  1021

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=154.0.8037.93); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff720579d55+5a55]
	chromedriver!(No symbol) [0x7ff72049f540]
	chromedriver!(No symbol) [0x7ff7202c45fd]
	chromedriver!(No symbol) [0x7ff7202aff82]
	chromedriver!(No symbol) [0x7ff7202d5c8c]
	chromedriver!(No symbol) [0x7ff720350a50]
	chromedriver!(No symbol) [0x7ff72036f5bd]
	chromedriver!(No symbol) [0x7ff720311a12]
	chromedriver!(No symbol) [0x7ff720312823]
	chromedriver!GetHandleVerifier [0x7ff7209904b1+41c1b1]
	chromedriver!GetHandleVerifier [0x7ff7209be26b+449f6b]
	chromedriver!GetHandleVerifier [0x7ff7209b274e+43e44e]
	chromedriver!GetHandleVerifier [0x7ff7206732fe+feffe]
	chromedriver!(No symbol) [0x7ff7204acb55]
	chromedriver!(No symbol) [0x7ff7204a7f64]
	chromedriver!(No symbol) [0x7ff7204a80f4]
	chromedriver!(No symbol) [0x7ff720492e4c]
	KERNEL32!BaseThreadInitThunk [0x7ffecaa5cd87+17]
	ntdll!RtlUserThreadStart [0x7ffecba6caec+2c]

In [19]:
x = p_name
y = p_eval
y2 = p_price
plt.bar(x,y,y2)

NameError: name 'plt' is not defined