In [1]:
import pandas as pd
df = pd.read_excel("file/score.xlsx",index_col="지원번호")

In [2]:
# 컬럼으로 찾는 방법, 인덱스로 찾는 방법
# 조건 : 필터 적용해서 조건적용
df['키'] >= 185
df[df['키'] >= 185]

# 변수로 입력받아 적용
filt = df['키'] >= 185
df[filt]
df[~filt] # ~ not적용

df2 = df[filt]
df3 = df2[['이름','키','국어']]
df3

       이름    키   국어
지원번호
1번    강나래  197   90
4번    김수찬  187   40
5번    김재욱  188   15
6번    박동현  202   80
7번    박혜정  188   55
8번    승근열  190  100

In [3]:
df3 = df2[df2['국어']>=80]
# df[[df['키']] >=185 and df['국어'] >= 90]
df[df['키']>=185]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85  Python
4번    김수찬   신림고  187   40   60   70  75  80     NaN
5번    김재욱   신림고  188   15   20   10  35  10     NaN
6번    박동현  디지털고  202   80  100   95  85  80       C
7번    박혜정  디지털고  188   55   65   45  40  35  PYTHON
8번    승근열  디지털고  190  100   85   90  95  95      C#

In [43]:
import pandas as pd
df = pd.read_excel("file/합계출산율_2026.xlsx",skiprows=28,usecols="A:K",nrows=2)
df

,Unnamed: 0,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,출생아 수,406.200,357.800,326.800,302.700,272.300,260.600,249.200,230.000,238.300,254.3
1,합계 출산율,1.172,1.052,0.977,0.918,0.837,0.808,0.778,0.721,0.748,0.8

In [ ]:
df1 =df.T
df1