In [46]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col="지원번호")

In [ ]:
# 컬럼 선택 : df['컬럼], 2개 이상은 []리스트로 추가
df[['이름','키','학교']] # 컬럼 순서를 바꿔서도 가능
df.columns # 컬럼명 전체 출력
df.columns[0] # 첫번째 컬럼명
df.columns[1]
df.columns[-1]
df['SW특기'] # sw특기 자료출력(컬럼의 자료 출력)
df[df.columns[-1]] # sw특기 자료출력(컬럼의 자료 출력)
# df[['이름','학교']] 
# df[df.columns[[0,3,-1]]] # 컬럼명을 여러개 사용해서 출력

       이름    학교
지원번호
1번    강나래   신림고
2번    강태원   신림고
3번    강호림   신림고
4번    김수찬   신림고
5번    김재욱   신림고
6번    박동현  디지털고
7번    박혜정  디지털고
8번    승근열  디지털고

In [ ]:
# 컬럼 슬라이싱
df['이름'] # df[컬럼명만 들어갈 수 있음] df[0:1] -> 불가

# rows에 대한 슬라이싱
df[0:3] # rows에 대한 슬라이싱
df['이름'][:3]
# df[["이름","학교","sw특기"]][2:]
df.iloc[[0,1,2]]

이름         강나래
학교         신림고
키          197
국어          90
영어          85
수학         100
과학          95
사회          85
SW특기    Python
Name: 1번, dtype: object

In [20]:
# 컬럼슬라이싱
df[df.columns[[0,3,-1]]] # 컬럼슬라이싱
df[df.columns[1:4]] # 컬럼슬라이싱
df.columns[1:4] # 컬럼명

Index(['학교', '키', '국어'], dtype='str')

In [29]:
df = pd.read_excel("file/연령별인구현황_2025.xlsx")
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,※ 매월 말일자 통계 현황,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 226,Unnamed: 227,Unnamed: 228,Unnamed: 229,Unnamed: 230,Unnamed: 231,Unnamed: 232,Unnamed: 233,Unnamed: 234,Unnamed: 235
0,NaN,NaN,2025년07월,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,계,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,행정기관코드,행정기관,총 인구수,연령구간인구수,0~9세,10~19세,20~29세,30~39세,40~49세,50~59세,...,10~19세,20~29세,30~39세,40~49세,50~59세,60~69세,70~79세,80~89세,90~99세,100세 이상
3,0000000000,전국,"51,159,889","51,159,889","3,024,945","4,630,054","5,800,511","6,649,487","7,627,071","8,684,663",...,"2,252,500","2,731,714","3,183,648","3,722,461","4,279,301","4,015,237","2,434,888","1,334,492","276,634","7,285"
4,1100000000,서울특별시,"9,323,492","9,323,492","468,816","721,320","1,283,295","1,453,915","1,370,576","1,479,906",...,"351,202","668,158","731,594","690,464","745,790","693,675","454,809","217,852","39,589","1,122"
5,2600000000,부산광역시,"3,251,625","3,251,625","174,385","264,105","347,001","388,293","464,061","533,582",...,"129,117","166,150","187,510","227,270","269,150","293,502","200,839","93,279","15,912",380
6,2700000000,대구광역시,"2,357,040","2,357,040","137,277","212,852","259,482","284,076","338,976","415,287",...,"103,673","120,683","132,982","168,373","211,040","198,463","123,774","64,137","11,751",244
7,2800000000,인천광역시,"3,041,215","3,041,215","191,580","275,205","343,681","427,940","474,175","517,186",...,"134,628","163,718","206,089","229,629","257,977","240,110","125,153","63,740","13,996",458
8,2900000000,광주광역시,"1,398,538","1,398,538","88,569","144,440","175,332","173,489","215,553","242,861",...,"69,794","81,483","83,278","106,651","121,311","101,060","61,179","31,734","6,292",166
9,3000000000,대전광역시,"1,440,682","1,440,682","88,295","135,988","190,311","193,281","210,477","243,133",...,"65,946","89,881","91,114","104,303","121,309","107,446","62,207","31,741","6,550",176
10,3100000000,울산광역시,"1,093,317","1,093,317","69,400","109,461","113,355","136,397","170,157","200,521",...,"52,823","46,580","61,167","81,241","98,972","88,639","44,472","18,631","3,489",89
11,3600000000,세종특별자치시,"392,154","392,154","39,786","53,598","36,705","58,404","76,817","58,448",...,"26,728","17,838","29,199","38,974","28,381","19,862","10,228","5,194","1,395",32
12,4100000000,경기도,"13,715,016","13,715,016","907,966","1,326,019","1,588,251","1,915,357","2,191,701","2,362,358",...,"648,817","742,934","915,920","1,068,642","1,170,928","986,112","527,550","279,834","58,507","1,633"
13,5100000000,강원특별자치도,"1,510,181","1,510,181","82,465","125,810","150,649","158,114","196,699","259,571",...,"60,644","65,189","73,267","95,523","124,755","139,733","84,538","55,039","11,453",341
14,4300000000,충청북도,"1,591,815","1,591,815","94,765","143,089","169,353","190,906","222,510","272,442",...,"69,467","74,640","86,257","106,113","131,858","132,773","77,318","48,254","10,635",265
15,4400000000,충청남도,"2,136,299","2,136,299","129,729","202,517","215,443","252,062","315,039","352,172",...,"98,037","94,918","113,744","146,403","165,330","166,044","106,496","69,342","17,347",392
16,5200000000,전북특별자치도,"1,729,337","1,729,337","90,407","160,265","175,875","172,529","229,830","300,777",...,"77,272","78,685","81,976","111,200","143,488","144,774","102,514","66,540","15,540",395
17,4600000000,전라남도,"1,782,183","1,782,183","97,751","155,618","163,051","169,648","229,537","306,612",...,"75,733","70,397","79,764","107,206","140,031","152,848","108,514","81,064","17,677",462
18,4700000000,경상북도,"2,516,753","2,516,753","133,226","215,714","226,544","253,958","337,104","437,680",...,"102,800","94,261","113,367","158,982","208,554","227,862","151,342","96,308","21,422",499
19,4800000000,경상남도,"3,214,016","3,214,016","184,989","314,002","295,003","343,941","480,612","582,384",...,"151,701","125,619","158,639","230,658","282,962","273,340","165,166","94,298","20,302",447
20,5000000000,제주특별자치도,"666,226","666,226","45,539","70,051","67,180","77,177","103,247","119,743",...,"34,118","30,580","37,781","50,829","57,465","48,994","28,789","17,505","4,777",184

In [ ]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols="C:D,H:I") # 파일 불러 오기 전
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

         총 인구수     연령구간인구수     30~39세     40~49세
0   51,159,889  51,159,889  6,649,487  7,627,071
1    9,323,492   9,323,492  1,453,915  1,370,576
2    3,251,625   3,251,625    388,293    464,061
3    2,357,040   2,357,040    284,076    338,976
4    3,041,215   3,041,215    427,940    474,175
5    1,398,538   1,398,538    173,489    215,553
6    1,440,682   1,440,682    193,281    210,477
7    1,093,317   1,093,317    136,397    170,157
8      392,154     392,154     58,404     76,817
9   13,715,016  13,715,016  1,915,357  2,191,701
10   1,510,181   1,510,181    158,114    196,699
11   1,591,815   1,591,815    190,906    222,510
12   2,136,299   2,136,299    252,062    315,039
13   1,729,337   1,729,337    172,529    229,830
14   1,782,183   1,782,183    169,648    229,537
15   2,516,753   2,516,753    253,958    337,104
16   3,214,016   3,214,016    343,941    480,612
17     666,226     666,226     77,177    103,247

In [ ]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)  # 파일 불러 오고 난 후
df[df.columns[[2,3,7,8]]] # 위의 내용을 이렇게 슬라이싱으로도 됨

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

         총 인구수     연령구간인구수     30~39세     40~49세
0   51,159,889  51,159,889  6,649,487  7,627,071
1    9,323,492   9,323,492  1,453,915  1,370,576
2    3,251,625   3,251,625    388,293    464,061
3    2,357,040   2,357,040    284,076    338,976
4    3,041,215   3,041,215    427,940    474,175
5    1,398,538   1,398,538    173,489    215,553
6    1,440,682   1,440,682    193,281    210,477
7    1,093,317   1,093,317    136,397    170,157
8      392,154     392,154     58,404     76,817
9   13,715,016  13,715,016  1,915,357  2,191,701
10   1,510,181   1,510,181    158,114    196,699
11   1,591,815   1,591,815    190,906    222,510
12   2,136,299   2,136,299    252,062    315,039
13   1,729,337   1,729,337    172,529    229,830
14   1,782,183   1,782,183    169,648    229,537
15   2,516,753   2,516,753    253,958    337,104
16   3,214,016   3,214,016    343,941    480,612
17     666,226     666,226     77,177    103,247

In [38]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)  # 파일 불러 오고 난 후
df[:1]['총 인구수'] # 하나만 가져올 경우

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0    51,159,889
Name: 총 인구수, dtype: str

In [ ]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)  # 파일 불러 오고 난 후
df[:1]['총 인구수'].str.replace(",","").astype('int') # 숫자형 문자열의 타입을 숫자로 변환할 때, 천단위 ,를 제거할 경우, 그리고 숫자로 변환할 경우, astype('int)로 변환

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0    51159889
Name: 총 인구수, dtype: int64

In [44]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
df.columns

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['행정기관코드', '행정기관', '총 인구수', '연령구간인구수', '0~9세', '10~19세', '20~29세',
       '30~39세', '40~49세', '50~59세',
       ...
       '10~19세.17', '20~29세.17', '30~39세.17', '40~49세.17', '50~59세.17',
       '60~69세.17', '70~79세.17', '80~89세.17', '90~99세.17', '100세 이상.17'],
      dtype='str', length=236)

In [64]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

In [65]:
df = pd.DataFrame(data)
df.set_index("영화",inplace=True)

In [66]:
df.to_excel("file/screen.xlsx")

In [67]:
df = pd.read_excel("file/screen.xlsx",index_col="영화")
df

           개봉 연도  관객 수    평점
영화
명량          2014  1761  8.88
극한직업        2019  1626  9.20
신과함께-죄와 벌   2017  1441  8.73
국제시장        2014  1426  9.16
괴물          2006  1301  8.62
도둑들         2012  1298  7.64
7번방의 선물     2013  1281  8.83
암살          2015  1270  9.10