In [ ]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# 컬럼 선택 : df['컬럼']명으로 찾음, 2개 이상은 [[]]리스트로 사용, 인덱스는 항상 같이 출력
df[['이름','키','학교']] # 컬럼 순서를 바꿔서도 가능
df.columns # 컬럼명 전체 출력
df.columns[0] # 첫번째 컬럼명
df.columns[1]
df.columns[-1]
df['SW특기'] # sw특기 자료출력(컬럼의 자료 출력)
df[df.columns[-1]] # sw특기 자료출력(컬럼명이 아니라 컬럼의 자료 출력)
# df[['이름','학교']] 
# df[df.columns[[0,3,-1]]] # 컬럼 위치를 여러개 사용해서 출력

# 컬럼 슬라이싱
df['이름'] # df[컬럼명만 들어갈 수 있음] df[0:1] -> 불가

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [ ]:
# rows에 대한 슬라이싱
df[0:3] # rows에 대한 슬라이싱
df['이름'][:3] # columns명, rows(숫자)
# df[["이름","학교","sw특기"]][2:]
df.iloc[[0,1,2]] # 숫자는 row만 나타냄

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [ ]:
# 컬럼슬라이싱
df[df.columns[[0,3,-1]]] # 컬럼명 슬라이싱
df[df.columns[1:4]] # 컬럼슬라이싱
# df.columns[1:4] # 컬럼명

Index(['학교', '키', '국어'], dtype='str')

In [ ]:
df = pd.read_excel("file/연령별인구현황_2025.xlsx",skiprows=3,usecols='B:D')
df[[3,7]]
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

KeyError: "None of [Index(['3', '7'], dtype='str')] are in the [columns]"

In [ ]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols="C:D,H:I") # 파일 불러 오기 전
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

         총 인구수     연령구간인구수     30~39세     40~49세
0   51,159,889  51,159,889  6,649,487  7,627,071
1    9,323,492   9,323,492  1,453,915  1,370,576
2    3,251,625   3,251,625    388,293    464,061
3    2,357,040   2,357,040    284,076    338,976
4    3,041,215   3,041,215    427,940    474,175
5    1,398,538   1,398,538    173,489    215,553
6    1,440,682   1,440,682    193,281    210,477
7    1,093,317   1,093,317    136,397    170,157
8      392,154     392,154     58,404     76,817
9   13,715,016  13,715,016  1,915,357  2,191,701
10   1,510,181   1,510,181    158,114    196,699
11   1,591,815   1,591,815    190,906    222,510
12   2,136,299   2,136,299    252,062    315,039
13   1,729,337   1,729,337    172,529    229,830
14   1,782,183   1,782,183    169,648    229,537
15   2,516,753   2,516,753    253,958    337,104
16   3,214,016   3,214,016    343,941    480,612
17     666,226     666,226     77,177    103,247

In [ ]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)  # 파일 불러 오고 난 후
df[df.columns[[2,3,7,8]]] # 위의 내용을 이렇게 슬라이싱으로도 됨

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

         총 인구수     연령구간인구수     30~39세     40~49세
0   51,159,889  51,159,889  6,649,487  7,627,071
1    9,323,492   9,323,492  1,453,915  1,370,576
2    3,251,625   3,251,625    388,293    464,061
3    2,357,040   2,357,040    284,076    338,976
4    3,041,215   3,041,215    427,940    474,175
5    1,398,538   1,398,538    173,489    215,553
6    1,440,682   1,440,682    193,281    210,477
7    1,093,317   1,093,317    136,397    170,157
8      392,154     392,154     58,404     76,817
9   13,715,016  13,715,016  1,915,357  2,191,701
10   1,510,181   1,510,181    158,114    196,699
11   1,591,815   1,591,815    190,906    222,510
12   2,136,299   2,136,299    252,062    315,039
13   1,729,337   1,729,337    172,529    229,830
14   1,782,183   1,782,183    169,648    229,537
15   2,516,753   2,516,753    253,958    337,104
16   3,214,016   3,214,016    343,941    480,612
17     666,226     666,226     77,177    103,247

In [38]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)  # 파일 불러 오고 난 후
df[:1]['총 인구수'] # 하나만 가져올 경우

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0    51,159,889
Name: 총 인구수, dtype: str

In [ ]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)  # 파일 불러 오고 난 후
df[:1]['총 인구수'].str.replace(",","").astype('int') # 숫자형 문자열의 타입을 숫자로 변환할 때, 천단위 ,를 제거할 경우, 그리고 숫자로 변환할 경우, astype('int)로 변환

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

0    51159889
Name: 총 인구수, dtype: int64

In [44]:
df=pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
df.columns

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['행정기관코드', '행정기관', '총 인구수', '연령구간인구수', '0~9세', '10~19세', '20~29세',
       '30~39세', '40~49세', '50~59세',
       ...
       '10~19세.17', '20~29세.17', '30~39세.17', '40~49세.17', '50~59세.17',
       '60~69세.17', '70~79세.17', '80~89세.17', '90~99세.17', '100세 이상.17'],
      dtype='str', length=236)

In [64]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

In [65]:
df = pd.DataFrame(data)
df.set_index("영화",inplace=True)

In [66]:
df.to_excel("file/screen.xlsx")

In [67]:
df = pd.read_excel("file/screen.xlsx",index_col="영화")
df

           개봉 연도  관객 수    평점
영화
명량          2014  1761  8.88
극한직업        2019  1626  9.20
신과함께-죄와 벌   2017  1441  8.73
국제시장        2014  1426  9.16
괴물          2006  1301  8.62
도둑들         2012  1298  7.64
7번방의 선물     2013  1281  8.83
암살          2015  1270  9.10