In [59]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col="지원번호")

In [ ]:
df['키'].max()
df['키'].nlargest(3) # 최대값 3개
df['키'].nsmallest(3) # 최대값 3개

df['학교'].unique() # 중복제거 후 분류
df['학교'].nunique() # 중복제거 후 개수

<StringArray>
['신림고', '디지털고']
Length: 2, dtype: str

In [33]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [34]:
# 컬럼의 기본정보 : 타입, 크기, 이름, null값 확인 -> describe는 str유형을 제외하고 기본 통계를 보여줌
# 자료 확인 시, null값 여부, 타입 확인해야 함. 그리고 이름, 갯수도 확인
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 640.0+ bytes

In [35]:
# 기본통계 확인 - 숫자타입인 경우, 기본적인 통계를 보여줌
df.describe()

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [41]:
# 자료의 크기 확인(8행, 9열) : rows = 8, columns = 9
df.shape
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [43]:
df.head() # 상단의 5개 줄만 볼 수 있음
df.head(3) # 3개까지만 볼 수 있음

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  신림고  197  90  85  100  95  85      Python
2번    강태원  신림고  184  40  35   50  55  25        Java
3번    강호림  신림고  168  80  75   70  80  75  Javascript

In [44]:
df.tail() # 하단의 5개만 확인
df.tail(2) # 하단의 2개만 확인 가능

       이름    학교    키   국어  영어  수학  과학  사회    SW특기
지원번호
7번    박혜정  디지털고  188   55  65  45  40  35  PYTHON
8번    승근열  디지털고  190  100  85  90  95  95      C#

In [45]:
df.values # 배열구조 확인
df.index # index 확인
df.columns # 컬럼 확인

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [ ]:
# 1차원 데이터(Series) : max, min, count, mean, std
df['키'].max() # 키의 최대값
# df['키'].min() # 키의 최소값
df['키'].count() # 갯수
df['키'].std() # 표준편차
df['키'].mean() # 평균

np.int64(202)

In [ ]:
df.describe()
df.max() # 열의 최대값 반환

In [70]:
df = pd.read_csv("file/drinks.csv")
df.describe()
df.info()
df.shape
df.head(10) # 대용량 자료인 경우, 앞의 몇개만 보고 싶은 경우
df.set_index('country',inplace=True)
df.sort_index(ascending=False)

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    str
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     170 non-null    str
dtypes: float64(1), int64(3), str(2)
memory usage: 9.2 KB

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Zimbabwe,64,18,4,4.7,AF
Zambia,32,19,4,2.5,AF
Yemen,6,0,0,0.1,AS
Vietnam,111,2,1,2.0,AS
Venezuela,333,100,3,7.7,SA
...,...,...,...,...,...
Angola,217,57,45,5.9,AF
Andorra,245,138,312,12.4,EU
Algeria,25,0,14,0.7,AF
Albania,89,132,54,4.9,EU
Afghanistan,0,0,0,0.0,AS

In [66]:
df = pd.read_excel("file/상장법인목록2.xlsx")
df

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,스톤브릿지벤처스,330730,기타 금융업,"창업투자, 사모투자",2022-02-25,12월,유승운,http://stonebridgeventures.vc,서울특별시
1,하나금융21호스팩,406760,금융 지원 서비스업,기업인수합병,2022-02-25,12월,이병찬,NaN,서울특별시
2,브이씨,365900,운동 및 경기용구 제조업,골프용 거리측정기,2022-02-24,12월,김준오,http://www.voicecaddie.co.kr,서울특별시
3,퓨런티어,370090,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외","전장카메라모듈장비, 모바일카메라모듈장비, PC및 광원",2022-02-23,12월,배상신,http://www.furonteer.com,경기도
4,바이오에프디엔씨,251120,기초 의약물질 및 생물학적 제제 제조업,식물세포 유래 유효물질 및 약리물질,2022-02-21,12월,"모상현, 정대현",http://www.biofdnc.com,인천광역시
...,...,...,...,...,...,...,...,...,...
2490,CJ대한통운,120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,강신호,http://www.cjlogistics.com,서울특별시
2491,메리츠화재,60,보험업,"손해보험(화재,해상,운송보험)",1956-07-02,12월,김용범,http://www.meritzfire.com,서울특별시
2492,경방,50,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2493,유수홀딩스,700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2494,한진중공업홀딩스,3480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,"조남호, 조원국",http://www.hhic-holdings.com,경기도

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2495 entries, 0 to 2494
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명     2495 non-null   str
 1   종목코드    2495 non-null   int64
 2   업종      2495 non-null   str
 3   주요제품    2477 non-null   str
 4   상장일     2495 non-null   datetime64[us]
 5   결산월     2495 non-null   str
 6   대표자명    2495 non-null   str
 7   홈페이지    2343 non-null   str
 8   지역      2495 non-null   str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 175.6 KB

In [68]:
df.describe()

                종목코드                         상장일
count    2495.000000                        2495
mean   125691.498998  2006-03-24 05:54:56.993988
min        20.000000         1956-03-03 00:00:00
25%     25895.000000         1999-12-21 00:00:00
50%     79370.000000         2008-07-11 00:00:00
75%    210760.000000         2016-11-28 12:00:00
max    950220.000000         2022-02-25 00:00:00
std    135624.466882                         NaN

In [69]:
df.head(10)

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,스톤브릿지벤처스,330730,기타 금융업,"창업투자, 사모투자",2022-02-25,12월,유승운,http://stonebridgeventures.vc,서울특별시
1,하나금융21호스팩,406760,금융 지원 서비스업,기업인수합병,2022-02-25,12월,이병찬,NaN,서울특별시
2,브이씨,365900,운동 및 경기용구 제조업,골프용 거리측정기,2022-02-24,12월,김준오,http://www.voicecaddie.co.kr,서울특별시
3,퓨런티어,370090,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외","전장카메라모듈장비, 모바일카메라모듈장비, PC및 광원",2022-02-23,12월,배상신,http://www.furonteer.com,경기도
4,바이오에프디엔씨,251120,기초 의약물질 및 생물학적 제제 제조업,식물세포 유래 유효물질 및 약리물질,2022-02-21,12월,"모상현, 정대현",http://www.biofdnc.com,인천광역시
5,한국제10호스팩,409570,금융 지원 서비스업,기업인수합병,2022-02-21,12월,김태훈,NaN,서울특별시
6,IBKS제17호스팩,405350,금융 지원 서비스업,금융 지원 서비스,2022-02-18,12월,이경준,NaN,서울특별시
7,인카금융서비스,211050,보험 및 연금관련 서비스업,보험 판매,2022-02-16,12월,최병채,http://www.incar.co.kr,서울특별시
8,나래나노텍,137080,특수 목적용 기계 제조업,"디스플레이 장비 (포토, 코팅, 모듈 장비)",2022-02-08,12월,정좌진,http://www.naraenano.co.kr,경기도
9,아셈스,136410,플라스틱제품 제조업,핫멜트 접착 필름,2022-02-07,12월,장지상,http://assems.com,부산광역시