In [ ]:
# 파일 저장, 읽기

import pandas as pd
data = {
    '이름':['강나래','강태원','강호림','김수찬','김재욱','박동현','박혜정','승근열'],
    '학교':['신림고','신림고','신림고','신림고','신림고','디지털고','디지털고','디지털고'] ,
    '키':[197,184,168,187,188,202,188,190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']}

df =pd.DataFrame(data, index=['1번','2번','3번','4번','5번','6번','7번','8번'])
df.index.name = '지원번호'

In [ ]:
# 파일 저장 : csv, txt, xlsx 형태로 저장 가능(database프로그램과 호환가능)
df.to_csv('file\\score.csv',encoding='utf-8-sig') # df자료를 csv 파일로 저장하겠다. 파일이름은 score, 엑셀에서도 읽을 수 있으려면 sig까지 입력. 안 읽으려면, utf-8까지만 입력하면 됨. python에서는 with open~형태

In [ ]:
# txt파일로 저장
df.to_csv("file/score.txt") # to_score까지는 같고, encoding 필요없음, 자료를 쉼표기준으로 분리
df.to_csv("file/score1.txt",sep="\t") # 이 파일은 자료를 탭 기준으로 분리, 임의의 문자 기준으로도 분리 가능

In [10]:
# xlsx 파일로 저장
df.to_excel('file/score.xlsx') #

In [ ]:
# 파일읽기 - read : csv, txt, xslx 읽을 수 있음
df = pd.read_csv('file/score.csv') # pandas로 csv파일인 score.csv파일을 읽어라
df

  지원번호         영화  개봉 연도  관객 수    평점
0   1번         명량   2014  1761  8.88
1   2번       극한직업   2019  1626  9.20
2   3번  신과함께-죄와 벌   2017  1441  8.73
3   4번       국제시장   2014  1426  9.16
4   5번         괴물   2006  1301  8.62
5   6번        도둑들   2012  1298  7.64
6   7번    7번방의 선물   2013  1281  8.83
7   8번         암살   2015  1270  9.10

In [25]:
# 파일읽기 - read : csv, txt, xslx 읽을 수 있음
df = pd.read_csv('file/score.csv',skiprows=1) # 읽을 때, 위의 1줄은 제거하고 읽어라
df

   1번         명량  2014  1761  8.88
0  2번       극한직업  2019  1626  9.20
1  3번  신과함께-죄와 벌  2017  1441  8.73
2  4번       국제시장  2014  1426  9.16
3  5번         괴물  2006  1301  8.62
4  6번        도둑들  2012  1298  7.64
5  7번    7번방의 선물  2013  1281  8.83
6  8번         암살  2015  1270  9.10

In [26]:
df = pd.read_csv('file/score.csv',skiprows=[1,3,5]) # 읽을 때, 위의 1,3,5번 줄은 제거하고 읽어라
df

  지원번호       영화  개봉 연도  관객 수    평점
0   2번     극한직업   2019  1626  9.20
1   4번     국제시장   2014  1426  9.16
2   6번      도둑들   2012  1298  7.64
3   7번  7번방의 선물   2013  1281  8.83
4   8번       암살   2015  1270  9.10

In [27]:
# nrows : 설정한 줄만큼 가져옴
df = pd.read_csv("file/score.csv",skiprows=1,nrows=4) # 첫줄은 제외하고, 다음 4줄을 가져오겠다.
df

   1번         명량  2014  1761  8.88
0  2번       극한직업  2019  1626  9.20
1  3번  신과함께-죄와 벌  2017  1441  8.73
2  4번       국제시장  2014  1426  9.16
3  5번         괴물  2006  1301  8.62

In [31]:
df = pd.read_csv('file/jumin08_2.csv',encoding='utf-8')
df

,행정구역,2026년08월_총인구수,2026년08월_세대수,2026년08월_세대당 인구,2026년08월_남자 인구수,2026년08월_여자 인구수,2026년08월_남여 비율
0,전국 (1000000000),"51,084,159","24,505,258",2.08,"25,412,088","25,672,071",0.99
1,서울특별시 (1100000000),"9,281,625","4,525,061",2.05,"4,466,290","4,815,335",0.93
2,전남광주통합특별시 (1200000000),"3,155,803","1,579,291",2.00,"1,578,180","1,577,623",1.00
3,부산광역시 (2600000000),"3,229,467","1,583,256",2.04,"1,568,318","1,661,149",0.94
4,대구광역시 (2700000000),"2,346,277","1,123,265",2.09,"1,148,130","1,198,147",0.96
5,인천광역시 (2800000000),"3,066,185","1,418,345",2.16,"1,530,650","1,535,535",1.00
6,대전광역시 (3000000000),"1,442,838","706,437",2.04,"718,413","724,425",0.99
7,울산광역시 (3100000000),"1,086,373","502,387",2.16,"560,121","526,252",1.06
8,세종특별자치시 (3600000000),"390,738","165,930",2.35,"194,589","196,149",0.99
9,경기도 (4100000000),"13,773,918","6,189,087",2.23,"6,914,277","6,859,641",1.01
10,강원특별자치도 (5100000000),"1,506,662","775,882",1.94,"757,981","748,681",1.01
11,충청북도 (4300000000),"1,601,367","808,665",1.98,"816,717","784,650",1.04
12,충청남도 (4400000000),"2,138,938","1,072,860",1.99,"1,098,834","1,040,104",1.06
13,전북특별자치도 (5200000000),"1,716,965","874,337",1.96,"855,796","861,169",0.99
14,경상북도 (4700000000),"2,492,677","1,303,782",1.91,"1,262,786","1,229,891",1.03
15,경상남도 (4800000000),"3,191,645","1,558,906",2.05,"1,609,943","1,581,702",1.02
16,제주특별자치도 (5000000000),"662,681","317,767",2.09,"331,063","331,618",1.00

In [32]:
df = pd.read_csv('file/jumin08_2.csv',skiprows=1, encoding='utf-8') # 첫줄을 건너뛰려면
df

,전국 (1000000000),"51,084,159","24,505,258",2.08,"25,412,088","25,672,071",0.99
0,서울특별시 (1100000000),"9,281,625","4,525,061",2.05,"4,466,290","4,815,335",0.93
1,전남광주통합특별시 (1200000000),"3,155,803","1,579,291",2.00,"1,578,180","1,577,623",1.00
2,부산광역시 (2600000000),"3,229,467","1,583,256",2.04,"1,568,318","1,661,149",0.94
3,대구광역시 (2700000000),"2,346,277","1,123,265",2.09,"1,148,130","1,198,147",0.96
4,인천광역시 (2800000000),"3,066,185","1,418,345",2.16,"1,530,650","1,535,535",1.00
5,대전광역시 (3000000000),"1,442,838","706,437",2.04,"718,413","724,425",0.99
6,울산광역시 (3100000000),"1,086,373","502,387",2.16,"560,121","526,252",1.06
7,세종특별자치시 (3600000000),"390,738","165,930",2.35,"194,589","196,149",0.99
8,경기도 (4100000000),"13,773,918","6,189,087",2.23,"6,914,277","6,859,641",1.01
9,강원특별자치도 (5100000000),"1,506,662","775,882",1.94,"757,981","748,681",1.01
10,충청북도 (4300000000),"1,601,367","808,665",1.98,"816,717","784,650",1.04
11,충청남도 (4400000000),"2,138,938","1,072,860",1.99,"1,098,834","1,040,104",1.06
12,전북특별자치도 (5200000000),"1,716,965","874,337",1.96,"855,796","861,169",0.99
13,경상북도 (4700000000),"2,492,677","1,303,782",1.91,"1,262,786","1,229,891",1.03
14,경상남도 (4800000000),"3,191,645","1,558,906",2.05,"1,609,943","1,581,702",1.02
15,제주특별자치도 (5000000000),"662,681","317,767",2.09,"331,063","331,618",1.00

In [36]:
df = pd.read_csv('file/score.csv',skiprows=1, nrows=4)
df

   1번         명량  2014  1761  8.88
0  2번       극한직업  2019  1626  9.20
1  3번  신과함께-죄와 벌  2017  1441  8.73
2  4번       국제시장  2014  1426  9.16
3  5번         괴물  2006  1301  8.62

In [45]:
# df = pd.read_csv("file/score.txt")
df = pd.read_csv("file/score.txt",sep='\t')
# df = pd.read_csv("file/score.txt",sep='*')
df
# df['이름']

           지원번호,이름,학교,키,국어,영어,수학,과학,사회,SW특기
0     1번,강나래,신림고,197,90,85,100,95,85,Python
1        2번,강태원,신림고,184,40,35,50,55,25,Java
2  3번,강호림,신림고,168,80,75,70,80,75,Javascript
3            4번,김수찬,신림고,187,40,60,70,75,80,
4            5번,김재욱,신림고,188,15,20,10,35,10,
5         6번,박동현,디지털고,202,80,100,95,85,80,C
6     7번,박혜정,디지털고,188,55,65,45,40,35,PYTHON
7        8번,승근열,디지털고,190,100,85,90,95,95,C#

In [ ]:
# xlsx파일 불러오기
# df = pd.read_excel("file/score.xlsx")
df = pd.read_excel("file/score.xlsx",index_col="지원번호") # 불러올 때, 인덱스를 지정할 수 있음
df

In [47]:
import pandas as pd
df.to_excel('file/score_2.xlsx',index=False) # 인덱스 제외 후 저장
df

           지원번호,이름,학교,키,국어,영어,수학,과학,사회,SW특기
0     1번,강나래,신림고,197,90,85,100,95,85,Python
1        2번,강태원,신림고,184,40,35,50,55,25,Java
2  3번,강호림,신림고,168,80,75,70,80,75,Javascript
3            4번,김수찬,신림고,187,40,60,70,75,80,
4            5번,김재욱,신림고,188,15,20,10,35,10,
5         6번,박동현,디지털고,202,80,100,95,85,80,C
6     7번,박혜정,디지털고,188,55,65,45,40,35,PYTHON
7        8번,승근열,디지털고,190,100,85,90,95,95,C#

In [49]:
df = pd.read_excel("file/score.xlsx",index_col="지원번호")
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#